1 "Timing lib db was not avaliable.\n"
	{}

2 "Failed to create analysis mode %s.\n"
	{}

3 "Failed to create analysis corner %s.\n"
	{}

4 "Failed to create analysis view %s.\n"
	{}

5 "Failed to get analysis mode in view %s.\n"
	{}

6 "Failed to get analysis view %s in timing lib db.\n"
	{}

7 "Got wrong for internal option -view in sdc command {%s}.\n"
	{}

8 "Missing internal option -view in sdc command {%s}, will use default view.\n"
	{}

9 "Failed to get or create analysis view %s in sdc command {%s}.\n"
	{}

10 "Failed to get value for option %s in sdc command {%s}.\n"
	{}

11 "Got wrong for option %s in sdc command {%s}.\n"
	{}

12 "Syntax error in sdc command {%s}.\n"
	{}

13 "Failed to add clock %s on pin or port %s in sdc command {%s}.\n"
	{}

14 "Found invalid pin or port %s in option %s during parsing sdc command {%s}.\n"
	{}

15 "Clock %s is not avaliable in sdc command {%s}.\n"
	{}

16 "Failed to update data for object %s in sdc command {%s}.\n"
	{}

17 "Failed to update data for pin or port %s in sdc command {%s}.\n"
	{}

18 "Failed to update data for pin pair {%s, %s} in sdc command {%s}.\n"
	{}

19 "Could not find cell %s in liberty %s during parsing sdc command {%s}.\n"
	{}

20 "Failed to update data for net %s in sdc command {%s}.\n"
	{}

21 "Only Sdc 2.1 was support now, please check command {%s}.\n"
	{}

22 "Sdc files were empty in command {%s}.\n"
	{}

23 "Failed to read sdc in analysis view %s.\n"
	{}

24 "Failed to get sdc in analysis view %s.\n"
	{}

25 "Could not open sdc file %s for write.\n"
	{}

26 "Error happended in sdc command {%s}, current design is %s, current instance is %s.\n"
	{}

27 "Sdc object was not ready when parsing sdc command {%s}.\n"
	{}

28 "Analysis view (id : %d) is invalid.\n"
	{}

29 "No view was found in mode %s.\n"
	{}

30 "Failed to get analysis corner in view %s.\n"
	{}

31 "No liberty avaliable in analysis corner %s.\n"
	{}

32 "No view was found in timing db.\n"
	{}

33 "Units were invalid in the first liberty during parsing sdc command {%s}.\n"
	{}

34 "Failed to get analysis corner %s in sdc command {%s}.\n"
	{}

35 "Failed to read sdc in view %s during parsing sdc command {%s}.\n"
	{}

36 "The option %s will be ignored (%s) during parsing sdc command {%s}.\n"
	{}

37 "%s during parsing sdc command {%s}.\n"
	{}