// skip comment
1 "fisrt message register testing by %s.\n"
	{detail message testing}

2 "empty testing.\n"
	{detail message testing 2}

3 "empty testing again.\n"
	{detail message testing 3}

4 "File name is null.\n"
	{}

5 "Mode is null.\n"
	{}

6 "Open file failed. file name: %s, mode: %s error: %s\n"
	{}

7 "Cannot open general file with compress level. file name: %s, mode: %s, level: %d .\n"
	{}

8 "Compress level: %d is not in [%d, %d].\n"
	{}

9 "Input IOBuffer is null.\n"
	{}

10 "Input IOBuffer's buffer is null.\n"
	{}

11 "Only support mode "r", "rb" and "rx" for zip file.\n"
	{}

12 "Input buffer is null.\n"
	{}

13 "Read total number of compressed blocks failed.\n"
	{}

14 "Read max size of decompressed blocks failed.\n"
	{}

15 "Lz4 compress buffer failed, compressed size is %d.\n"
	{}

16 "Lz4 decompress buffer failed, decompressed size is %d.\n"
	{}

17 "Support only one file in a zip file.\n"
	{}

18 "Malloc buffer failed for compressing zip file.\n"
	{}

19 "Do not support seeking a zip file.\n"
	{}

20 "Do not support flushing a zip file.\n"
	{}

21 "Do not support telling a zip file.\n"
	{}

22 "Read Lz4 magic number failed.\n"
	{}

23 "Malloc buffer failed.\n"
	{}

24 "%X is not Lz4 mangic number %X.\n"
	{}

25 "Do not support writing a zip file.\n"
	{}

26 "Lz4 decompress failed, error: %s\n"
	{}

27 "Zip compress failed, return code is: %d\n"
	{}

28 "Lz4 read failed.\n"
	{}

29 "Read buffer is null.\n"
	{}

30 "Compression failed, error: %s\n"
	{}

31 "End of frame error : %s\n"
	{}

32 "Can't create LZ4 decompress context file name: %s error: %s\n"
	{}

33 "Can't create LZ4 compress context file name: %s error: %s\n"
	{}

34 "Number of buffers is not equal to number of sizes.\n"
	{}

35 "Create pthread for writing compress block filed.\n"
	{}

36 "Can't create ZSTD decompress context : file name: %s, error: %s\n"
	{}

37 "Can't create ZSTD compress context : file name: %s, error: %s\n"
	{}

38 "Read Zstd magic number failed.\n"
	{}

39 "Malloc Zstd src buffer failed.\n"
	{}

40 "%X is not Zstd mangic number %X.\n"
	{}

41 "Read Zstd file failed, error: %s.\n"
	{}

42 "Decompress Zstd failed, error: %s.\n"
	{}

43 "Compress Zstd failed, error: %s.\n"
	{}

44 "%s: gettimeofday(), error: %s.\n"
	{}

45 "%s: getrusage(), error: %s.\n"
	{}

46 "%s\n"
	{}

47 "%s: fopen fail, error: %s.\n"
	{}

48 "%s: pthread_create fail, error: %s.\n"
	{}

49 "%s: pthread_rwlock_init, error: %s.\n"
	{}

