// skip comment
// read_def/read_lef
1 "Returned user data is not correct.\n"
	{}

2 "Callback type is out of bounds.\n"
	{}

3 "  %s extension %s.\n"
	{}

4 "This callback is not used.\n"
	{}

5 "%s.\n"
	{}

6 "Could not open input file '%s'.\n"
	{}

7 "Reader returns bad status.\n"
	{}

8 "Aliases do not work.\n"
	{}

9 "Cannot find property definition %s.\n"
	{}

10 "BOGUS geometries type.\n"
	{}

11 "Design name is null pointer when reading DEF DESIGN.\n"
	{}

12 "Cannot find top cell when reading DEF DESIGN.\n"
	{}

13 "%s is not a valid bus.\n"
	{}

14 "Create %s %s failed.\n"
	{}

15 "Too many input files, max = %d.\n"
	{}

16 "io %s is null pointer.\n"
	{}

17 "Cannot find floorplan when read DEF %s.\n"
	{}

18 "Polygon table is null pointer in top cell.\n"
	{}

19 "Cannot find the via: %s.\n"
	{}

20 "Cannot find Tech LEF when DEF blockage.\n"
	{}

21 "Cannot find layer %s in LEF.\n"
	{}

22 "Cannot find component %s in blockage.\n"
	{}

23 "Create %s failed.\n"
	{}

24 "Pin has different net definition, Pin %s, Net %s.\n"
	{}

25 "Invalid site orient %d.\n"
	{}

26 "Cannot find site %s.\n"
	{}

27 "Cannot find techlib when read DEF ndr_rule.\n"
	{}

28 "SaveGroupMember input name is null.\n"
	{}

29 "Malloc failed when read DEF GROUP's compNamePattern.\n"
	{}

30 "Cannot find instance %s .\n"
	{}

31 "There is a mismatch between DEF UNITS %d and original defined UNITS %d, so the DEF UNITS is discarded.\n"
	{}

32 "Oxide %d out of range.\n"
	{}

// read_lef
33 "Cannot find layer % in Via %s.\n"
	{}

// read_verilog
34 "Cannot find cell %s -- inst is deleted.\n"
	{}

35 "Cell %s does't has term %s.\n"
	{}

36 "Create %s %s failed for module %s.\n"
	{}

37 "Range misses msb or lsb for port or net %s.\n"
	{}

38 "Create pin %s failed for instance %s in module %s.\n"
	{}

39 "Cannot find net %s in module %s.\n"
	{}

40 "Cannot find net %s in assign of module %s.\n"
	{}

41 "Option -top is not set.\n"
	{}

// read_write_db
42 "Failed to open output db file %s.\n"
	{}

43 "Get file header size failed.\n"
	{}

// write_def
44 "Cannot find %s when writting DEF file.\n"
	{}

45 "Open DEF file failed %s.\n"
	{}

46 "Write DEF file %s failed.\n"
	{}

47 "Cannot find %s %d when writting DEF file.\n"
	{}

// write_verilog
48 "Cannot get %s vector from id %d of cell %s.\n"
	{}

49 "Cannot get %s from id %d of cell %s.\n"
	{}

50 "Cannot get master cell for instance %s.\n"
	{}

51 "Cannot get %s from id %d of instance %s.\n"
	{}

52 "Cannot find cell with id %d.\n"
	{}

53 "No file name.\n"
	{}

54 "Cannot open file %s for writing: %s.\n"
	{}

55 "Write verilog %s failed.\n"
	{}
