// skip comment
1 "Creating %s %s failed.\n"
	{}

2 "More than one %s %s exists.\n"
	{}

3 "Could not open %s for writing.\n"
	{}

4 "Please specify the %s file.\n"
	{}

5 "The file %s specified does not exist.\n"
	{}

6 "Cannot find %s when %s.\n"
	{}

7 "No value specified for "%s" option.\n"
	{}

8 "%sRead %s successfully.\n"
	{}

9 "Failed to %s.\n"
	{}

10 "The name "%s" is for internal use only.\nPlease use other name.\n"
	{}

11 "Cannot find the %s %s.\n"
	{}

12 "Value "%s" is not a valid value for "%s" option, please correct it.\n"
	{}

13 "Setting view %s status successfully.\n"
	{}

14 "%s"
	{}

15 "%s (%s).\n"
	{}

16 "Command line option syntax error, please refer to help.\n"
	{}

17 "Error happened during reading sdc files in view %s .\n"
	{}

18 "%s already exists, please specify another one.\n"
	{}

19 "Syntax error in tcl command {%s} .\n"
	{}

20 "Failed to get value for option %s in tcl command {%s} .\n"
	{}

21 "Failed to exec tcl commands in multi mode multi corner file %s .\n"
	{}

22 "Timing lib db was not avaliable during reading tcl command {%s} .\n"
	{}

23 "Invalid view was found in timing lib db.\n"
	{}

24 "Invalid mode was found in analysis view %s.\n"
	{}

25 "No sdc files in mode %s.\n"
	{}

26 "Failed to get sdc file contents in mode %s.\n"
	{}

